### ISSUE TITLE
Would you accept a pull request to add support for setting DISTSTYLE?

### ISSUE THREAD

**Issue by jerryclinesmith** [ValiMail/postshift#15]
We have some tables that we use DISTSTYLE = "ALL".  Happy to do the work, but wanted to check that you would accept it first.

**Comment by petergoldstein** [comment]
@jerryclinesmith Obviously can't commit without seeing the PR, but we'd definitely review/consider it.  Thanks.

**Comment by jerryclinesmith** [comment]
Closing this, we ended up just using raw SQL to get around some other issues...
